// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdbwdyqwpbmrextmtusy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkYndkeXF3cGJtcmV4dG10dXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MTEwMTUsImV4cCI6MjA2MzE4NzAxNX0.A9shPE3i2ANtFtRBUuUCM_Mu9T5Jl6ZO1F_iOzrbsu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);